### ISSUE TITLE
Termination of Referee if clients are not responsive 

### ISSUE THREAD

**Issue by mahi97** [fira-simurosot/Referee#4]
Referee application as the central hub of messages and architecture should always be up and running regardless of situation of the clients or simulator.

**Comment by peng1999** [comment]
Yes some sort of reconnect mechanism is needed. We can pause the referee when one of the clients disconnects.

**Comment by mahi97** [comment]
I think in most cases we can just ignore and let the client connect again.
I'm not sure if we need separated threads or processes.

**Comment by peng1999** [comment]
> I think in most cases we can just ignore and let the client connect again.

This approach is inefficient because the client is actually a passive gRPC *server*. The referee will try connecting it again and again if we do this.

Also, in real contest, we often need a pause when one side crashs.

**Comment by peng1999** [comment]
Closed by bae6695abdf7f80795b3298050a3a165e20297c0
