### ISSUE TITLE
code related to Test function and the Simulate function

### ISSUE THREAD

**Issue by worry80** [fira-simurosot/Referee#5]
When I debuged this module and replace the Test function with Simulate function, I noticed that the RobotId in Test function is not same as it in Simulate function. The RobotId of the second team in the packet sent by FIRASim starts from 5, but the RobotId of the second team in Test function starts from 0. However, the SimEnvironment2MatchInfo function only handles the format in the Test function, which caused the "  System.IndexOutOfRangeException: Index was outside the bounds of the array." when I used the Simulate function , so I hope to change the RobotId in the Test function to correct format and modify SimEnvironment2MatchInfo properly.

**Comment by peng1999** [comment]
Feel free to open a pull request. This code base still has some bug and we will fix it soon.

**Comment by peng1999** [comment]
Solved in https://github.com/fira-simurosot/Referee/pull/6#issuecomment-601645783
